FROM python:3.10-slim

WORKDIR /app

# Install only runtime deps (NO apt-get)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
